[phases.setup]
nixPkgs = ["nodejs_20", "npm", "corepack"]

[phases.install]
cmds = [
  "cd homeops-backend && npm install",
  "corepack enable && cd homeops-frontend && pnpm install"
]

[phases.build]
cmds = ["cd homeops-backend && npm run build"]

[start]
cmd = "cd homeops-backend && npm start"
