"use strict";

/**
 * Switchable outbound email types (SES or Customer.io).
 * Auth and ops emails are not listed here — they always use SES.
 */
const SWITCHABLE_EMAIL_TYPES = {
  welcome: {
    label: "Welcome",
    description: "Sent when a user completes onboarding (self-serve signup) and has no property yet.",
    customerIoDefaultEvent: "welcome_sent",
    mergeVariables: [
      { key: "recipientFirstName", description: "User first name (Hi {{recipientFirstName}},)" },
      { key: "ctaUrl", description: "Link to add a property (e.g. /{account}/properties/new)" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  account_invitation: {
    label: "Account invitation",
    description: "Sent when a user is invited to join an account on Opsy.",
    customerIoDefaultEvent: "account_invitation_sent",
    mergeVariables: [
      { key: "inviteUrl", description: "Accept invitation link" },
      { key: "inviterName", description: "Name of the person who sent the invite" },
      { key: "inviteeName", description: "Invitee first name (optional; used in “Hi {{inviteeName}},”)" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  property_invitation: {
    label: "Property invitation",
    description: "Sent when a user is invited to join a property.",
    customerIoDefaultEvent: "property_invitation_sent",
    mergeVariables: [
      { key: "inviteUrl", description: "Accept invitation link" },
      { key: "inviterName", description: "Name of the person who sent the invite" },
      { key: "inviteeName", description: "Invitee first name (optional; used in “Hi {{inviteeName}},”)" },
      { key: "recipientFirstName", description: "Invitee first name for agent-branded templates (Hi {{recipientFirstName}},)" },
      { key: "propertyAddress", description: "Full property address" },
      { key: "propertyAddressSuffix", description: "Property suffix for subject line, e.g. “: 123 Main St”" },
      { key: "inviteeHasAccount", description: "Whether invitee already has an Opsy account" },
      { key: "invitedByAgent", description: "True when an agent invited a homeowner (branch campaigns on this)" },
      { key: "agentFirstName", description: "Agent first name (headline, sign-off, CTA)" },
      { key: "agentFullName", description: "Agent full name (shown under avatar)" },
      { key: "agentRole", description: "Agent role label, e.g. real estate advisor" },
      { key: "agentAvatarUrl", description: "Always-valid agent avatar image URL (real photo or branded initials fallback). Use this for the email <img>." },
      { key: "agentPhotoUrl", description: "Agent photo URL; empty when the agent has no uploaded/OAuth photo. Use for branching only." },
      { key: "agentInitials", description: "Agent initials for avatar fallback (e.g. AO)" },
      { key: "hasAgentPhoto", description: "True when the agent has a real photo (agentPhotoUrl is set)" },
      { key: "emailIconPlace", description: "Feature row icon URL (uploaded in Email Delivery)" },
      { key: "emailIconAlert", description: "Feature row icon URL (uploaded in Email Delivery)" },
      { key: "emailIconHome", description: "Feature row icon URL (uploaded in Email Delivery)" },
      { key: "propertyStreet", description: "Street line for follow-up copy (address_line_1 or first line of address)" },
      { key: "missingDataCount", description: "Number of data gaps detected on the property (for follow-up emails)" },
      { key: "missingDataSummary", description: "Comma-separated gap titles, e.g. Documents, Roof, Heating" },
      { key: "missingDataHtml", description: "Pre-rendered HTML rows for the beige gap card in Customer.io" },
      { key: "missingDataItem1Title", description: "Gap card row 1 title" },
      { key: "missingDataItem1Body", description: "Gap card row 1 body" },
      { key: "missingDataItem2Title", description: "Gap card row 2 title" },
      { key: "missingDataItem2Body", description: "Gap card row 2 body" },
      { key: "missingDataItem3Title", description: "Gap card row 3 title" },
      { key: "missingDataItem3Body", description: "Gap card row 3 body" },
      { key: "teamName", description: "Agent team name (footer co-brand, left)" },
      { key: "brokerageName", description: "Agency name (footer co-brand, right)" },
      { key: "brokerageLogoUrl", description: "Brokerage logo URL (absolute)" },
      { key: "personalNoteBlock", description: "HTML block for optional personal message" },
      { key: "inviteInstructions", description: "Instructions paragraph before the accept button" },
      { key: "ctaLabel", description: "Button label text" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  bulk_property_invitation: {
    label: "Bulk property invitation",
    description: "Single email listing multiple property invitations.",
    customerIoDefaultEvent: "bulk_property_invitation_sent",
    mergeVariables: [
      { key: "inviterName", description: "Name of the person who sent the invite" },
      { key: "inviteeName", description: "Invitee first name (optional; used in “Hi {{inviteeName}},”)" },
      { key: "inviteeHasAccount", description: "Whether invitee already has an Opsy account" },
      { key: "items", description: "Array of { propertyAddress, inviteUrl } objects" },
      { key: "itemCount", description: "Number of properties invited" },
      { key: "bulkInviteInstructions", description: "Instructions paragraph before property links" },
      { key: "listHtml", description: "HTML list of invitation links" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  contractor_report: {
    label: "Contractor maintenance report",
    description: "Request sent to a contractor to fill out a maintenance report.",
    customerIoDefaultEvent: "contractor_report_requested",
    mergeVariables: [
      { key: "reportUrl", description: "Link to the report form" },
      { key: "contractorName", description: "Contractor name" },
      { key: "propertyAddress", description: "Property address" },
      { key: "systemName", description: "System name" },
      { key: "senderName", description: "Homeowner who requested the report (defaults to “A homeowner”)" },
      { key: "propertyAtPhrase", description: "Optional phrase: “ for the property at …”" },
      { key: "systemPhrase", description: "Optional phrase: “ regarding …”" },
      { key: "origin", description: "Origin URL" },
      { key: "inspectionDate", description: "Date of inspection" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  schedule_notification: {
    label: "Schedule notification",
    description: "Notifies a contractor that a service has been scheduled.",
    customerIoDefaultEvent: "service_scheduled",
    mergeVariables: [
      { key: "contractorName", description: "Contractor name" },
      { key: "propertyAddress", description: "Property address" },
      { key: "systemName", description: "System name" },
      { key: "scheduledDate", description: "Scheduled date (YYYY-MM-DD)" },
      { key: "scheduledTime", description: "Scheduled time (HH:MM)" },
      { key: "formattedDate", description: "Human-readable date" },
      { key: "formattedTime", description: "Human-readable time" },
      { key: "messageBody", description: "Message from homeowner" },
      { key: "senderName", description: "Homeowner name" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  professional_contact: {
    label: "Professional directory contact",
    description: "Message from a homeowner to a professional via the directory.",
    customerIoDefaultEvent: "professional_contact_sent",
    mergeVariables: [
      { key: "professionalCompanyName", description: "Professional company name" },
      { key: "message", description: "Message body" },
      { key: "senderName", description: "Sender name" },
      { key: "senderEmail", description: "Sender email (Reply-To)" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  communication_notify: {
    label: "Communication notification",
    description: "Notifies a user that a new in-app communication is available.",
    customerIoDefaultEvent: "communication_notify_sent",
    mergeVariables: [
      { key: "userName", description: "Recipient name" },
      { key: "subjectLine", description: "Communication subject" },
      { key: "viewUrl", description: "Link to view in app" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  support_ticket_received: {
    label: "Support ticket received",
    description: "Confirmation sent when a user submits a support or feedback ticket.",
    customerIoDefaultEvent: "support_ticket_received",
    mergeVariables: [
      { key: "ticketSubject", description: "Ticket subject" },
      { key: "ticketType", description: "support or feedback" },
      { key: "autoResponseText", description: "Automated acknowledgment text" },
      { key: "viewUrl", description: "Link to view ticket" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  support_ticket_reply: {
    label: "Support ticket reply",
    description: "Notification when a team member replies to a support ticket.",
    customerIoDefaultEvent: "support_ticket_reply",
    mergeVariables: [
      { key: "userName", description: "Ticket creator name" },
      { key: "ticketSubject", description: "Ticket subject" },
      { key: "ticketStatus", description: "Current ticket status" },
      { key: "replyBody", description: "Reply message body" },
      { key: "viewUrl", description: "Link to view ticket" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_active: {
    label: "Agent coverage started",
    description: "Sent to a homeowner when their agent's plan begins covering their property.",
    customerIoDefaultEvent: "sponsorship_active",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "agentName", description: "Sponsoring agent name" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_grace_started: {
    label: "Agent coverage grace started",
    description: "Sent when an agent leaves/drops their plan, starting the homeowner's 30-day grace period.",
    customerIoDefaultEvent: "sponsorship_grace_started",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "agentName", description: "Former sponsoring agent name" },
      { key: "graceEndsOn", description: "Date the grace period ends" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_grace_reminder: {
    label: "Agent coverage grace reminder",
    description: "Reminder sent during the grace period that coverage ends soon.",
    customerIoDefaultEvent: "sponsorship_grace_reminder",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "graceEndsOn", description: "Date the grace period ends" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_ended: {
    label: "Agent coverage ended",
    description: "Sent when the grace period expires and the property reverts to the free plan.",
    customerIoDefaultEvent: "sponsorship_ended",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
};

const EMAIL_TYPE_KEYS = Object.keys(SWITCHABLE_EMAIL_TYPES);

module.exports = {
  SWITCHABLE_EMAIL_TYPES,
  EMAIL_TYPE_KEYS,
};
