"use strict";

/**
 * Switchable outbound email types (SES or Customer.io).
 * Auth and ops emails are not listed here — they always use SES.
 */
const SWITCHABLE_EMAIL_TYPES = {
  welcome: {
    label: "Welcome",
    description: "Sent when a user completes onboarding (self-serve signup) and has no property yet.",
    customerIoDefaultEvent: "welcome_sent",
    mergeVariables: [
      { key: "recipientFirstName", description: "User first name (Hi {{recipientFirstName}},)" },
      { key: "ctaUrl", description: "Link to add a property (e.g. /{account}/properties/new)" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  account_invitation: {
    label: "Account invitation",
    description: "Sent when a user is invited to join an account on Opsy.",
    customerIoDefaultEvent: "account_invitation_sent",
    mergeVariables: [
      { key: "inviteUrl", description: "Accept invitation link (use {{ event.inviteUrl }} in Customer.io)" },
      { key: "inviterName", description: "Full name of the person who sent the invite" },
      { key: "senderFirstName", description: "Inviter first name (headline personalization)" },
      { key: "avatarUrl", description: "Inviter avatar URL (empty when no photo; template should default to brand mark)" },
      { key: "inviteeName", description: "Invitee first name (optional; used in “Hi {{ event.inviteeName }},”)" },
      { key: "recipientFirstName", description: "Same as inviteeName when only email is known" },
      { key: "userRole", description: "Platform role of invitee: agent, homeowner, or admin. Branch Customer.io journey on this." },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  property_invitation: {
    label: "Property invitation",
    description: "Sent when a user is invited to join a property.",
    customerIoDefaultEvent: "property_invitation_sent",
    mergeVariables: [
      { key: "inviteUrl", description: "Accept invitation link" },
      { key: "inviterName", description: "Name of the person who sent the invite" },
      { key: "inviteeName", description: "Invitee first name (optional; used in “Hi {{inviteeName}},”)" },
      { key: "recipientFirstName", description: "Invitee first name for agent-branded templates (Hi {{recipientFirstName}},)" },
      { key: "propertyAddress", description: "Full property address" },
      { key: "propertyAddressSuffix", description: "Property suffix for subject line, e.g. “: 123 Main St”" },
      { key: "inviteeHasAccount", description: "Whether invitee already has an Opsy account" },
      { key: "invitedByAgent", description: "True when an agent invited a homeowner (branch campaigns on this)" },
      { key: "agentFirstName", description: "Agent first name (headline, sign-off, CTA)" },
      { key: "agentFullName", description: "Agent full name (shown under avatar)" },
      { key: "agentRole", description: "Agent role label, e.g. real estate advisor" },
      { key: "agentAvatarUrl", description: "Always-valid agent avatar image URL (real photo or branded initials fallback). Use this for the email <img>." },
      { key: "agentPhotoUrl", description: "Agent photo URL; empty when the agent has no uploaded/OAuth photo. Use for branching only." },
      { key: "agentInitials", description: "Agent initials for avatar fallback (e.g. AO)" },
      { key: "hasAgentPhoto", description: "True when the agent has a real photo (agentPhotoUrl is set)" },
      { key: "emailIconPlace", description: "Feature row icon URL (uploaded in Email Delivery)" },
      { key: "emailIconAlert", description: "Feature row icon URL (uploaded in Email Delivery)" },
      { key: "emailIconHome", description: "Feature row icon URL (uploaded in Email Delivery)" },
      { key: "propertyStreet", description: "Street line for follow-up copy (address_line_1 or first line of address)" },
      { key: "missingDataCount", description: "Number of data gaps detected on the property (for follow-up emails)" },
      { key: "missingDataSummary", description: "Comma-separated gap titles, e.g. Documents, Roof, Heating" },
      { key: "missingDataHtml", description: "Pre-rendered HTML rows for the beige gap card in Customer.io" },
      { key: "missingDataItem1Title", description: "Gap card row 1 title" },
      { key: "missingDataItem1Body", description: "Gap card row 1 body" },
      { key: "missingDataItem2Title", description: "Gap card row 2 title" },
      { key: "missingDataItem2Body", description: "Gap card row 2 body" },
      { key: "missingDataItem3Title", description: "Gap card row 3 title" },
      { key: "missingDataItem3Body", description: "Gap card row 3 body" },
      { key: "teamName", description: "Agent team name (footer co-brand, left)" },
      { key: "brokerageName", description: "Agency name (footer co-brand, right)" },
      { key: "brokerageLogoUrl", description: "Brokerage logo URL (absolute)" },
      { key: "personalNoteBlock", description: "HTML block for optional personal message" },
      { key: "inviteInstructions", description: "Instructions paragraph before the accept button" },
      { key: "ctaLabel", description: "Button label text" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  bulk_property_invitation: {
    label: "Bulk property invitation",
    description: "Single email listing multiple property invitations.",
    customerIoDefaultEvent: "bulk_property_invitation_sent",
    mergeVariables: [
      { key: "inviterName", description: "Name of the person who sent the invite" },
      { key: "inviteeName", description: "Invitee first name (optional; used in “Hi {{inviteeName}},”)" },
      { key: "inviteeHasAccount", description: "Whether invitee already has an Opsy account" },
      { key: "items", description: "Array of { propertyAddress, inviteUrl } objects" },
      { key: "itemCount", description: "Number of properties invited" },
      { key: "bulkInviteInstructions", description: "Instructions paragraph before property links" },
      { key: "listHtml", description: "HTML list of invitation links" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  contractor_report: {
    label: "Contractor maintenance report",
    description: "Request sent to a contractor to fill out a maintenance report.",
    customerIoDefaultEvent: "contractor_report_requested",
    mergeVariables: [
      { key: "reportUrl", description: "Link to the report form" },
      { key: "contractorName", description: "Contractor name" },
      { key: "propertyAddress", description: "Property address" },
      { key: "systemName", description: "System name" },
      { key: "senderName", description: "Homeowner who requested the report (defaults to “A homeowner”)" },
      { key: "propertyAtPhrase", description: "Optional phrase: “ for the property at …”" },
      { key: "systemPhrase", description: "Optional phrase: “ regarding …”" },
      { key: "origin", description: "Origin URL" },
      { key: "inspectionDate", description: "Date of inspection" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  schedule_notification: {
    label: "Schedule notification",
    description: "Notifies a contractor that a service has been scheduled.",
    customerIoDefaultEvent: "service_scheduled",
    mergeVariables: [
      { key: "contractorName", description: "Contractor name" },
      { key: "propertyAddress", description: "Property address" },
      { key: "systemName", description: "System name" },
      { key: "scheduledDate", description: "Scheduled date (YYYY-MM-DD)" },
      { key: "scheduledTime", description: "Scheduled time (HH:MM)" },
      { key: "formattedDate", description: "Human-readable date" },
      { key: "formattedTime", description: "Human-readable time" },
      { key: "messageBody", description: "Message from homeowner" },
      { key: "senderName", description: "Homeowner name" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  professional_contact: {
    label: "Professional directory contact",
    description: "Message from a homeowner to a professional via the directory.",
    customerIoDefaultEvent: "professional_contact_sent",
    mergeVariables: [
      { key: "professionalCompanyName", description: "Professional company name" },
      { key: "message", description: "Message body" },
      { key: "senderName", description: "Sender name" },
      { key: "senderEmail", description: "Sender email (Reply-To)" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  contractor_bid_inquiry: {
    label: "Bid clarifying questions",
    description: "Questions sent to a contractor about a quote or bid.",
    customerIoDefaultEvent: "contractor_bid_inquiry_sent",
    mergeVariables: [
      { key: "contractorName", description: "Contractor first name or company" },
      { key: "actionItemTitle", description: "Action item / project title" },
      { key: "message", description: "Message body" },
      { key: "senderName", description: "Sender name" },
      { key: "senderEmail", description: "Sender email (Reply-To)" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  communication_notify: {
    label: "Communication notification",
    description: "Notifies a user that a new in-app communication is available.",
    customerIoDefaultEvent: "communication_notify_sent",
    mergeVariables: [
      { key: "userName", description: "Recipient name" },
      { key: "subjectLine", description: "Communication subject" },
      { key: "viewUrl", description: "Link to view in app" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  support_ticket_received: {
    label: "Support ticket received",
    description: "Confirmation sent when a user submits a support or feedback ticket.",
    customerIoDefaultEvent: "support_ticket_received",
    mergeVariables: [
      { key: "ticketSubject", description: "Ticket subject" },
      { key: "ticketType", description: "support or feedback" },
      { key: "autoResponseText", description: "Automated acknowledgment text" },
      { key: "viewUrl", description: "Link to view ticket" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  support_ticket_reply: {
    label: "Support ticket reply",
    description: "Notification when a team member replies to a support ticket.",
    customerIoDefaultEvent: "support_ticket_reply",
    mergeVariables: [
      { key: "userName", description: "Ticket creator name" },
      { key: "ticketSubject", description: "Ticket subject" },
      { key: "ticketStatus", description: "Current ticket status" },
      { key: "replyBody", description: "Reply message body" },
      { key: "viewUrl", description: "Link to view ticket" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_active: {
    label: "Agent coverage started",
    description: "Sent to a homeowner when their agent's plan begins covering their property.",
    customerIoDefaultEvent: "sponsorship_active",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "agentName", description: "Sponsoring agent name" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_grace_started: {
    label: "Agent coverage grace started",
    description: "Sent when an agent leaves/drops their plan, starting the homeowner's 30-day grace period.",
    customerIoDefaultEvent: "sponsorship_grace_started",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "agentName", description: "Former sponsoring agent name" },
      { key: "graceEndsOn", description: "Date the grace period ends" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_grace_reminder: {
    label: "Agent coverage grace reminder",
    description: "Reminder sent during the grace period that coverage ends soon.",
    customerIoDefaultEvent: "sponsorship_grace_reminder",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "graceEndsOn", description: "Date the grace period ends" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  sponsorship_ended: {
    label: "Agent coverage ended",
    description: "Sent when the grace period expires and the property reverts to the free plan.",
    customerIoDefaultEvent: "sponsorship_ended",
    mergeVariables: [
      { key: "userName", description: "Homeowner name" },
      { key: "propertyLabel", description: "Property address/label" },
      { key: "billingUrl", description: "Link to the billing page" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  helpdesk_inspection_review_created: {
    label: "Helpdesk: inspection report review",
    description:
      "Internal alert when a new inspection report review is queued. Recipients: kino@heyopsy.com and dev@heyopsy.com.",
    customerIoDefaultEvent: "helpdesk_inspection_review_created",
    mergeVariables: [
      { key: "propertyAddress", description: "Property address" },
      { key: "customerName", description: "Customer / uploader name" },
      { key: "customerEmail", description: "Customer email" },
      { key: "reviewId", description: "Inspection analysis result ID" },
      { key: "jobId", description: "Analysis job ID" },
      { key: "uploadedAt", description: "Upload timestamp (formatted)" },
      { key: "reviewUrl", description: "Link to the review in Helpdesk" },
      { key: "detailsHtml", description: "Pre-rendered details table HTML" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  helpdesk_ticket_created_ops: {
    label: "Helpdesk: new ticket (ops)",
    description:
      "Internal alert when a support, feedback, or data adjustment ticket is created. Recipient: dev@heyopsy.com.",
    customerIoDefaultEvent: "helpdesk_ticket_created_ops",
    mergeVariables: [
      { key: "ticketId", description: "Ticket ID" },
      { key: "ticketType", description: "support, feedback, or data_adjustment" },
      { key: "ticketTypeLabel", description: "Human-readable ticket type" },
      { key: "ticketSubject", description: "Ticket subject" },
      { key: "ticketUrl", description: "Link to the ticket in Helpdesk" },
      { key: "accountName", description: "Account name" },
      { key: "accountId", description: "Account ID" },
      { key: "createdByName", description: "Submitter name" },
      { key: "createdByEmail", description: "Submitter email" },
      { key: "descriptionHtml", description: "Pre-rendered description block HTML" },
      { key: "detailsHtml", description: "Pre-rendered details table HTML" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  demo_account_opened: {
    label: "Demo account opened",
    description:
      "Internal alert when a prospect first logs into a ready-to-use demo account. Recipients: kino@, success@, and dirk.snel@heyopsy.com.",
    customerIoDefaultEvent: "demo_account_opened",
    mergeVariables: [
      { key: "userName", description: "Demo account name" },
      { key: "userEmail", description: "Demo account email" },
      { key: "userRole", description: "agent or homeowner" },
      { key: "userId", description: "User ID" },
      { key: "demoExpiresAt", description: "Demo expiry timestamp (formatted)" },
      { key: "demoFirstLoginAt", description: "First login timestamp (formatted)" },
      { key: "provisionedByName", description: "Super admin who provisioned the account" },
      { key: "adminUrl", description: "Link to the user in admin" },
      { key: "detailsHtml", description: "Pre-rendered details table HTML" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  demo_account_expired: {
    label: "Demo account expired",
    description:
      "Internal alert when a ready-to-use demo account reaches its expiry time. Recipients: kino@, success@, and dirk.snel@heyopsy.com.",
    customerIoDefaultEvent: "demo_account_expired",
    mergeVariables: [
      { key: "userName", description: "Demo account name" },
      { key: "userEmail", description: "Demo account email" },
      { key: "userRole", description: "agent or homeowner" },
      { key: "userId", description: "User ID" },
      { key: "demoExpiresAt", description: "Demo expiry timestamp (formatted)" },
      { key: "demoFirstLoginAt", description: "First login timestamp (formatted), if opened" },
      { key: "wasOpened", description: "Whether the prospect logged in before expiry" },
      { key: "provisionedByName", description: "Super admin who provisioned the account" },
      { key: "adminUrl", description: "Link to the user in admin" },
      { key: "detailsHtml", description: "Pre-rendered details table HTML" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  plan_selected_ops: {
    label: "Plan selected (ops)",
    description:
      "Internal alert when a user picks a free/zero-cost plan or completes Stripe Checkout for a paid plan. Recipients: kino@, dirk.snel@, and dev@heyopsy.com.",
    customerIoDefaultEvent: "plan_selected_ops",
    mergeVariables: [
      { key: "userName", description: "User name" },
      { key: "userEmail", description: "User email" },
      { key: "userRole", description: "User role" },
      { key: "userId", description: "User ID" },
      { key: "accountId", description: "Account ID" },
      { key: "accountName", description: "Account name" },
      { key: "accountUrl", description: "Account URL slug" },
      { key: "planCode", description: "Plan code" },
      { key: "planName", description: "Plan display name" },
      { key: "paidLabel", description: "Paid or Free" },
      { key: "billingInterval", description: "Billing interval (month/year)" },
      { key: "amountPaid", description: "Formatted amount paid (Checkout)" },
      { key: "source", description: "onboarding, upgrade_downgrade, or stripe_checkout" },
      { key: "sourceLabel", description: "Human-readable source" },
      { key: "detailsHtml", description: "Pre-rendered details table HTML" },
      { key: "brandName", description: "Product brand name" },
    ],
  },
  homeaversary_homeowner: {
    label: "Homeaversary (homeowner)",
    description:
      "Congratulates a homeowner on another year with their property on the last-sale anniversary.",
    customerIoDefaultEvent: "homeaversary",
    mergeVariables: [
      { key: "audience", description: "homeowner or agent. Branch the Homeaversary Customer.io campaign on this." },
      { key: "recipientFirstName", description: "Homeowner first name (Hi {{ event.recipientFirstName }},)" },
      { key: "propertyAddress", description: "Property address" },
      { key: "propertyUrl", description: "Link to the property in Opsy" },
      { key: "yearsOwned", description: "Whole years since last sale (e.g. 3)" },
      { key: "yearsOwnedPlural", description: "Empty when yearsOwned is 1, otherwise \"s\"" },
      { key: "anniversaryDate", description: "Human-readable anniversary date" },
      { key: "lastSaleDate", description: "Original last sale date (YYYY-MM-DD)" },
      { key: "ownerName", description: "Homeowner / owner label (empty on the homeowner path)" },
      { key: "brandName", description: "Product brand name" },
      { key: "tasksCompletedCount", description: "Completed maintenance records in the last 12 months" },
      { key: "documentsUploadedCount", description: "Documents added in the last 12 months" },
      { key: "systemsServicedCount", description: "Distinct home systems serviced in the last 12 months" },
      { key: "hasYearInReview", description: "\"true\" when at least one completed task is listed" },
      { key: "yearInReviewHtml", description: "Pre-rendered list of completed tasks (or empty-state copy)" },
      { key: "milestoneHtml", description: "Pre-rendered three-column year / tasks / documents row" },
      { key: "milestone1Title", description: "Years owned (e.g. 7 Years)" },
      { key: "milestone1Body", description: "Street label under years owned" },
      { key: "milestone2Title", description: "Task count, or fallback \"Memories made\"" },
      { key: "milestone2Body", description: "Task subtitle" },
      { key: "milestone3Title", description: "Document count, or fallback \"Here for you\"" },
      { key: "milestone3Body", description: "Document subtitle" },
    ],
  },
  homeaversary_agent: {
    label: "Homeaversary (agent preview)",
    description:
      "Reminds the property's agent one week before a Homeaversary so they can send a note.",
    customerIoDefaultEvent: "homeaversary",
    mergeVariables: [
      { key: "audience", description: "homeowner or agent. Branch the Homeaversary Customer.io campaign on this." },
      { key: "recipientFirstName", description: "Agent first name (Hi {{ event.recipientFirstName }},)" },
      { key: "propertyAddress", description: "Property address" },
      { key: "propertyUrl", description: "Link to the property in Opsy" },
      { key: "yearsOwned", description: "Whole years the homeowner will celebrate" },
      { key: "yearsOwnedPlural", description: "Empty when yearsOwned is 1, otherwise \"s\"" },
      { key: "anniversaryDate", description: "Human-readable anniversary date" },
      { key: "lastSaleDate", description: "Original last sale date (YYYY-MM-DD)" },
      { key: "ownerName", description: "Homeowner / owner label for the property" },
      { key: "brandName", description: "Product brand name" },
      { key: "tasksCompletedCount", description: "Completed maintenance records in the last 12 months" },
      { key: "documentsUploadedCount", description: "Documents added in the last 12 months" },
      { key: "systemsServicedCount", description: "Distinct home systems serviced in the last 12 months" },
      { key: "hasYearInReview", description: "\"true\" when at least one completed task is listed" },
      { key: "yearInReviewHtml", description: "Pre-rendered list of completed tasks (or empty-state copy)" },
      { key: "milestoneHtml", description: "Pre-rendered three-column year / tasks / documents row" },
      { key: "milestone1Title", description: "Years owned (e.g. 7 Years)" },
      { key: "milestone1Body", description: "Street label under years owned" },
      { key: "milestone2Title", description: "Task count, or fallback \"Memories made\"" },
      { key: "milestone2Body", description: "Task subtitle" },
      { key: "milestone3Title", description: "Document count, or fallback \"Here for you\"" },
      { key: "milestone3Body", description: "Document subtitle" },
    ],
  },
};

const EMAIL_TYPE_KEYS = Object.keys(SWITCHABLE_EMAIL_TYPES);

/** Internal demo ops alerts that may send even when outbound email is suppressed on demo. */
const DEMO_OPS_EMAIL_TYPES = new Set([
  "demo_account_opened",
  "demo_account_expired",
]);

function isDemoOpsEmailType(emailType) {
  return DEMO_OPS_EMAIL_TYPES.has(emailType);
}

module.exports = {
  SWITCHABLE_EMAIL_TYPES,
  EMAIL_TYPE_KEYS,
  DEMO_OPS_EMAIL_TYPES,
  isDemoOpsEmailType,
};
