/**
 * Field metadata for standard system detail forms (Systems tab).
 * Used by SystemEditableFormCards to render identity-card style editable fields.
 */

const CONDITION_OPTIONS = ["Excellent", "Good", "Fair", "Poor"];

export const SYSTEM_FIELD_DEFINITIONS = {
  roofMaterial: {
    label: "Material",
    type: "select",
    options: [
      "Built Up",
      "Cedar Shake",
      "Composition",
      "Flat",
      "Green (Living)",
      "Metal",
      "Tile",
      "Torch Down",
      "Other",
    ],
    group: "identity",
  },
  roofInstallDate: { label: "Install Date", type: "date", group: "identity" },
  roofInstaller: { label: "Installer", type: "installer", group: "identity" },
  roofCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  roofWarranty: { label: "Warranty", type: "warranty-select", group: "condition" },
  roofLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  roofNextInspection: { label: "Next Inspection", type: "date", group: "inspection" },
  roofIssues: { label: "Known Issues", type: "textarea", group: "issues", fullWidth: true },

  gutterMaterial: {
    label: "Material",
    type: "select",
    options: ["Aluminum", "Copper", "Vinyl", "Other"],
    group: "identity",
  },
  gutterInstallDate: { label: "Install Date", type: "date", group: "identity" },
  gutterInstaller: { label: "Installer", type: "installer", group: "identity" },
  gutterCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  gutterLastInspection: {
    label: "Last Cleaning",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  gutterGuards: {
    label: "Gutter Guards",
    type: "select",
    options: ["Yes", "No"],
    group: "condition",
  },
  gutterNextInspection: {
    label: "Next Cleaning Date",
    type: "date",
    group: "inspection",
  },
  gutterIssues: { label: "Known Issues", type: "textarea", group: "issues", fullWidth: true },

  foundationType: { label: "Foundation Type", type: "text", group: "identity" },
  foundationCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  foundationLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  foundationNextInspection: {
    label: "Next Inspection",
    type: "date",
    group: "inspection",
  },
  foundationIssues: {
    label: "Known Issues",
    type: "textarea",
    group: "issues",
    fullWidth: true,
  },

  sidingType: { label: "Siding Type", type: "text", group: "identity" },
  sidingInstallDate: { label: "Install Date", type: "date", group: "identity" },
  sidingInstaller: { label: "Installer", type: "installer", group: "identity" },
  sidingCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  sidingLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  sidingNextInspection: { label: "Next Inspection", type: "date", group: "inspection" },
  sidingIssues: { label: "Known Issues", type: "textarea", group: "issues", fullWidth: true },

  windowType: { label: "Window Type", type: "text", group: "identity" },
  windowInstallDate: { label: "Install Date", type: "date", group: "identity" },
  windowInstaller: { label: "Installer", type: "installer", group: "identity" },
  windowCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  windowWarranty: { label: "Warranty", type: "warranty-select", group: "condition" },
  windowLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  windowNextInspection: { label: "Next Inspection", type: "date", group: "inspection" },
  windowIssues: { label: "Known Issues", type: "textarea", group: "issues", fullWidth: true },

  heatingSystemType: { label: "System Type", type: "text", group: "identity" },
  heatingInstallDate: { label: "Install Date", type: "date", group: "identity" },
  heatingInstaller: { label: "Installer", type: "installer", group: "identity" },
  heatingCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  heatingWarranty: { label: "Warranty", type: "warranty-select", group: "condition" },
  heatingLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  heatingNextInspection: { label: "Next Inspection", type: "date", group: "inspection" },
  heatingLocation: { label: "Location", type: "text", group: "identity" },
  heatingIssues: { label: "Known Issues", type: "textarea", group: "issues", fullWidth: true },

  acSystemType: { label: "System Type", type: "text", group: "identity" },
  acInstallDate: { label: "Install Date", type: "date", group: "identity" },
  acInstaller: { label: "Installer", type: "installer", group: "identity" },
  acCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  acWarranty: { label: "Warranty", type: "warranty-select", group: "condition" },
  acLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  acNextInspection: { label: "Next Inspection", type: "date", group: "inspection" },
  acLocation: { label: "Location", type: "text", group: "identity" },
  acIssues: { label: "Known Issues", type: "textarea", group: "issues", fullWidth: true },

  waterHeatingSystemType: { label: "System Type", type: "text", group: "identity" },
  waterHeatingInstallDate: { label: "Install Date", type: "date", group: "identity" },
  waterHeatingInstaller: { label: "Installer", type: "installer", group: "identity" },
  waterHeatingCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  waterHeatingWarranty: {
    label: "Warranty",
    type: "warranty-select",
    group: "condition",
  },
  waterHeatingLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  waterHeatingNextInspection: {
    label: "Next Inspection",
    type: "date",
    group: "inspection",
  },
  waterHeatingIssues: {
    label: "Known Issues",
    type: "textarea",
    group: "issues",
    fullWidth: true,
  },

  electricalServiceAmperage: {
    label: "Service Amperage",
    type: "text",
    group: "identity",
  },
  electricalInstallDate: { label: "Install Date", type: "date", group: "identity" },
  electricalInstaller: { label: "Installer", type: "installer", group: "identity" },
  electricalCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  electricalWarranty: {
    label: "Warranty",
    type: "warranty-select",
    group: "condition",
  },
  electricalLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  electricalNextInspection: {
    label: "Next Inspection",
    type: "date",
    group: "inspection",
  },
  electricalLocation: { label: "Panel Location", type: "text", group: "identity" },
  electricalIssues: {
    label: "Known Issues",
    type: "textarea",
    group: "issues",
    fullWidth: true,
  },

  plumbingSupplyMaterials: {
    label: "Supply Materials",
    type: "text",
    group: "identity",
  },
  plumbingWasteType: { label: "Waste Type", type: "text", group: "identity" },
  plumbingInstallDate: { label: "Install Date", type: "date", group: "identity" },
  plumbingInstaller: { label: "Installer", type: "installer", group: "identity" },
  plumbingCondition: {
    label: "Condition",
    type: "select",
    options: CONDITION_OPTIONS,
    group: "condition",
  },
  plumbingWarranty: {
    label: "Warranty",
    type: "warranty-select",
    group: "condition",
  },
  plumbingLastInspection: {
    label: "Last Inspection",
    type: "date",
    group: "inspection",
    disableWhenNewInstall: true,
  },
  plumbingNextInspection: {
    label: "Next Inspection",
    type: "date",
    group: "inspection",
  },
  plumbingMainTurnoffLocation: {
    label: "Main Turnoff Location",
    type: "text",
    group: "identity",
  },
  plumbingClearoutLocation: {
    label: "Clearout Location",
    type: "text",
    group: "identity",
  },
  plumbingIssues: {
    label: "Known Issues",
    type: "textarea",
    group: "issues",
    fullWidth: true,
  },

  safetySmokeCOCoverage: {
    label: "Smoke/CO Coverage",
    type: "text",
    group: "identity",
  },
  safetyGFCIStatus: { label: "GFCI Status", type: "text", group: "identity" },
  safetyKnownHazards: {
    label: "Known Hazards (asbestos, lead, poly, knob & tube, etc.)",
    type: "textarea",
    group: "issues",
    fullWidth: true,
  },
};

/** Ordered field names per standard system id. */
export const SYSTEM_FIELDS_BY_ID = {
  roof: [
    "roofMaterial",
    "roofInstallDate",
    "roofInstaller",
    "roofCondition",
    "roofWarranty",
    "roofLastInspection",
    "roofNextInspection",
    "roofIssues",
  ],
  gutters: [
    "gutterMaterial",
    "gutterInstallDate",
    "gutterInstaller",
    "gutterCondition",
    "gutterLastInspection",
    "gutterGuards",
    "gutterNextInspection",
    "gutterIssues",
  ],
  foundation: [
    "foundationType",
    "foundationCondition",
    "foundationLastInspection",
    "foundationNextInspection",
    "foundationIssues",
  ],
  exterior: [
    "sidingType",
    "sidingInstallDate",
    "sidingInstaller",
    "sidingCondition",
    "sidingLastInspection",
    "sidingNextInspection",
    "sidingIssues",
  ],
  windows: [
    "windowType",
    "windowInstallDate",
    "windowInstaller",
    "windowCondition",
    "windowWarranty",
    "windowLastInspection",
    "windowNextInspection",
    "windowIssues",
  ],
  heating: [
    "heatingSystemType",
    "heatingInstallDate",
    "heatingInstaller",
    "heatingCondition",
    "heatingWarranty",
    "heatingLastInspection",
    "heatingNextInspection",
    "heatingLocation",
    "heatingIssues",
  ],
  ac: [
    "acSystemType",
    "acInstallDate",
    "acInstaller",
    "acCondition",
    "acWarranty",
    "acLastInspection",
    "acNextInspection",
    "acLocation",
    "acIssues",
  ],
  waterHeating: [
    "waterHeatingSystemType",
    "waterHeatingInstallDate",
    "waterHeatingInstaller",
    "waterHeatingCondition",
    "waterHeatingWarranty",
    "waterHeatingLastInspection",
    "waterHeatingNextInspection",
    "waterHeatingIssues",
  ],
  electrical: [
    "electricalServiceAmperage",
    "electricalInstallDate",
    "electricalInstaller",
    "electricalCondition",
    "electricalWarranty",
    "electricalLastInspection",
    "electricalNextInspection",
    "electricalLocation",
    "electricalIssues",
  ],
  plumbing: [
    "plumbingSupplyMaterials",
    "plumbingWasteType",
    "plumbingInstallDate",
    "plumbingInstaller",
    "plumbingCondition",
    "plumbingWarranty",
    "plumbingLastInspection",
    "plumbingNextInspection",
    "plumbingMainTurnoffLocation",
    "plumbingClearoutLocation",
    "plumbingIssues",
  ],
  safety: ["safetySmokeCOCoverage", "safetyGFCIStatus", "safetyKnownHazards"],
};

/** Next inspection form field per standard system id. */
export const NEXT_INSPECTION_FIELD_BY_SYSTEM = {
  roof: "roofNextInspection",
  gutters: "gutterNextInspection",
  foundation: "foundationNextInspection",
  exterior: "sidingNextInspection",
  windows: "windowNextInspection",
  heating: "heatingNextInspection",
  ac: "acNextInspection",
  waterHeating: "waterHeatingNextInspection",
  electrical: "electricalNextInspection",
  plumbing: "plumbingNextInspection",
};

/** Install date field used to compute age display per system. */
export const INSTALL_DATE_FIELD_BY_SYSTEM = {
  roof: "roofInstallDate",
  gutters: "gutterInstallDate",
  exterior: "sidingInstallDate",
  windows: "windowInstallDate",
  heating: "heatingInstallDate",
  ac: "acInstallDate",
  waterHeating: "waterHeatingInstallDate",
  electrical: "electricalInstallDate",
  plumbing: "plumbingInstallDate",
};

/** Yes/no inspection rows for the inspections system detail form. */
export const INSPECTION_TOGGLE_FIELDS = [
  { toggle: "generalInspection", date: "generalInspectionDate", link: "generalInspectionLink", label: "General Inspection" },
  { toggle: "roofInspection", date: "roofInspectionDate", link: "roofInspectionLink", label: "Roof Inspection" },
  { toggle: "sewerScope", date: "sewerScopeDate", link: "sewerScopeLink", label: "Sewer Scope" },
  { toggle: "hvacInspection", date: "hvacInspectionDate", link: "hvacInspectionLink", label: "HVAC Inspection" },
  { toggle: "pestInspection", date: "pestInspectionDate", link: "pestInspectionLink", label: "Pest Inspection" },
  { toggle: "otherInspection", date: "otherInspectionDate", link: "otherInspectionLink", label: "Other Inspection" },
];
